### ISSUE TITLE
AI Updates

### ISSUE THREAD

**Issue by logankilpatrick** [TheComputerM/julia-games#1]
Hey, @TheComputerM  I think from a gameplay point of view it would be cool to make a few updates: 

When the user clicks, have the AI's next move take a couple of seconds. During that time, make it so that the player cannot click any buttons. This will make it seem like the AI is actually thinking.

**Comment by TheComputerM** [comment]
@logankilpatrick Yes I will add it, I have to use the `sleep()` function right?

**Comment by logankilpatrick** [comment]
Yeah that is what I would do

**Comment by TheComputerM** [comment]
Done.

**Comment by TheComputerM** [comment]
@logankilpatrick https://github.com/TheComputerM/julia-games/commit/1c4e14d5f95af66516b66077346a4ef196cfa870
