### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by abhishalya** [TheComputerM/julia-games#2]
Hey good work into both games, but I just saw the GIF representing the game against computer in tictactoe, and it is obviously broken.

1. The computer is making dumb moves.
2. The computer (O) wins, although the player (X) should win the game.

These are important changes required for this game to even work!

You should at least use the [minmax](https://www.geeksforgeeks.org/minimax-algorithm-in-game-theory-set-1-introduction/) algorithm for the computer moves.

**Comment by TheComputerM** [comment]
@abhishalya  Yeah, just noticed that, will update the game.

**Comment by logankilpatrick** [comment]
Good catch!

**Comment by TheComputerM** [comment]
Forgot about it for a while, but fixed it and added minimax algorithm: https://github.com/TheComputerM/julia-games/commit/7c72ebb3ba0c1c84fc6dbb08b45272ab724d929d
